### PR TITLE
Fixed log-implementation for GLSL float packing

### PR DESCRIPTION
**Pull request by flash1293**
This implementation bug fixes the problem that numbers >-1.0 && <1.0 are not retrieved correctly

### CODE REVIEW

**Comment by MaiaVictor** [comment]
Is this up-to-date? I'm not sure I've seen this PR 25 days ago (!?) but last time I checked numbers were working fine. Aren't they?

**Comment by cazala** [comment]
Yeah, it seems it's broken =(

```js
var monkeys = require("webmonkeys")();

// it works
monkeys.set("a", [1]);
monkeys.set("b", [0]);
monkeys.work(16, "b(i) := a(i);");
console.log(monkeys.get("b")); // [1]

// it doesn't work =(
monkeys.set("a", [0.5]);
monkeys.set("b", [0]);
monkeys.work(16, "b(i) := a(i);");
console.log(monkeys.get("b")); // [5.960464477539063e-8]
```

**Comment by cazala** [comment]
:+1: I just tested this change in my local copy of webmonkeys and it solves the bug 

fixed

**Comment by MaiaVictor** [comment]
Weird, sorry for missing this.

**Pull request merged**
