### PR TITLE
using an ArrayBuffer with TypedArray improves initialisation

### PR DESCRIPTION
**Pull request by thysultan**
using an ArrayBuffer to create monkeyIndexArray -> initialisation 3X++ faster.

```
var buffer = new ArrayBuffer((2048*2048)|0);
var monkeyIndexArray = new Int32Array(buffer);
...
new Float32Array(monkeyIndexArray)
``` 

typed array /w buffer: 38.11500000000001
typed array: 128.70000000000002
normal array: 174.52500000000003

ops/s

[https://esbench.com/bench/57c1f350db965b9a00965c94](https://esbench.com/bench/57c1f350db965b9a00965c94)

### CODE REVIEW

**Comment by MaiaVictor** [comment]
Are you sure this is correct? I think `new ArrayBuffer((2048*2048)|0)` will create a buffer with `2048*2048` bytes. Since an Int32 is 4 bytes, `monkeyIndexArray` will only 1/4 of its original capacity, reducing the max num of parallel monkeys.

**Comment by thysultan** [comment]
You're right this is actually wrong.

**Comment by MaiaVictor** [comment]
Hey, if you are interested in working in this problem, I think I great solution to the startup issue would be to create a small array initially (64*64?). Then, on the work function, something like: 
    
    if (monkeyCount > maxMonkeys) { 
      maxMonkeys = fixTextureSide(monkeyCount); 
      monkeyArrayIndex = ...; 
      gl.bindBuffer(gl.ARRAY_BUFFER, rangebuffer);
      gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(monkeyIndexArray), gl.STATIC_DRAW);
    }

**Comment by thysultan** [comment]
@MaiaVictor  something like this also seems to have a 2-3X speed bump.

```
var length = (2048*2048)|0;
var UHEAP8  = new Uint8Array(length);
var UHEAP32 = new Uint32Array(UHEAP8.buffer);
var HEAP    = new Int32Array(UHEAP32.buffer);

for (var i=0; i < maxMonkeys; ++i) {
    HEAP[i] = i;
}
```

That with the suggestion that you mentioned and it seems to come up to 90X faster, though instead of 64*64 i think a good initial heap of 1024*1024 will account for more cases before updating the heap comes into play, or you could expose a method that can be explicitly called to up the heap.

```
var maxMonkeys = (1024*1024)|0;
...
if (monkeyCount > maxMonkeys) {
...
}
```

**Comment by thysultan** [comment]
[Benchmark](https://esbench.com/bench/57c1f350db965b9a00965c94)

**Pull request closed without merging**
